myapp/urls.py
from django.conf.urls import include, url
from django.contrib import  admin
from rest_framework import routers
from restaurant import views


urlpatterns = [
  url(r'^api/menus', views.MenuViewSet),
    url(r'^api/orders/', views.OrderViewSet),
    url(r'^api/info/', views.InfoViewSet),
    url(r'^api/rating/', views.RaitingViewSet),
    url(r'^admin/', admin.site.urls),
    url(r'^restaurant/', include('restaurant.urls', namespace='restaurant')),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

restaurant/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^menus/$', views.index,name='index'),
    url(r'^orders/$', views.index_o,name='index_o'),

    url(r'^menus/(?P<menu_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^orders/(?P<order_id>[0-9]+)/$', views.detail_o, name='detail_o'),


    url(r'^today/$', views.index_t,name='index_t'),
    url(r'^menu/add/$', views.post_new, name='post_new'),
    url(r'^order/add/$', views.post_order	, name='post_order'),
    url(r'^change/(?P<order_id>[0-9]+)/$', views.change, name='change'),
]
		

restaurant/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
import datetime
from datetime import datetime

ORDER_PROCESSING = 0
ORDER_SHIPPING = 1
ORDER_ENDED = 2

STATUS_ORDER = (
    (ORDER_PROCESSING, 'Procesing'),
    (ORDER_SHIPPING, 'Shiping'),
    (ORDER_ENDED, 'Ended'),
)





class Menu (models.Model):
    title=models.CharField(max_length=500)
    dish1=models.CharField(max_length=500)
    dish2=models.CharField(max_length=500)
    desert=models.CharField(max_length=500)
    date_day=models.DateField(blank=True, null=True,auto_now_add=True)

    def get_absolute_ulr (self):
        return reverse('restaurant:detail',kwargs={'pk':self.pk})

    def __unicode__(self):
        return self.title + " ----- " + str(self.date_day)



class Order (models.Model):
    title=models.ForeignKey(Menu)
    name=models.CharField(max_length=255)
    email=models.EmailField(max_length=100)
    phone=models.CharField(max_length=100)
    adress=models.CharField(max_length=500)
    status = models.IntegerField(default=0, choices=STATUS_ORDER)
    raiting = models.FloatField(default=0)
    date_order=models.DateTimeField(blank=True, null=True, auto_now_add=True)

    def __unicode__(self):
         return '%s - %s' % (self.name, self.title)

restaurant/forms.py
from django import forms
from .models import Menu,Order
import datetime



class MenuForm(forms.ModelForm):

    # date_day = forms.DateField(widget=forms.SelectDateWidget())
    date_day = forms.CharField()
    def __init__(self, *args, **kwargs):
        super(MenuForm, self).__init__(*args, **kwargs)

        # self.fields['date_day'].required=True
        self.fields['title'].widget = forms.TextInput(attrs={'placeholder':'titlul meniului'})
        self.fields['date_day'].widget = forms.TextInput(attrs={'placeholder':'Introduceti data', 'type':'date'})
        self.fields['date_day'].initial = datetime.datetime.now().date()
        self.fields['dish1'].widget = forms.TextInput(attrs={'placeholder':'Introduceti felul 1'})
        self.fields['dish2'].widget = forms.TextInput(attrs={'placeholder':'Introduceti felu 2'})
        self.fields['desert'].widget = forms.TextInput(attrs={'placeholder':'Introduceti desertul'})


        # self.fields['date_day'].initial = datetime.datetime.now

    class Meta:
        model = Menu
        fields = ('__all__')

    def clean(self):
        # cleaned_data = self.cleaned_data
        cleaned_data = self.cleaned_data,

    def clean_date_day(self):
        date_day_string = self.cleaned_data['date_day']
        try:
            date_day = datetime.datetime.strptime(date_day_string, '%Y-%m-%d').date()
        except Exception, e:
            raise forms.ValidationError("Data nu are formatul corect!")


        if date_day < datetime.date.today():
            raise forms.ValidationError("Data nu poate fi din trecut!")
        return date_day


class OrderForm(forms.ModelForm):

    date_order = forms.DateField(widget=forms.SelectDateWidget())

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)

        self.fields['date_order'].required=True
        self.fields['title'].help_text = 'Introduceti titlul meniului'
        self.fields['name'].help_text = 'Introduceti numele'
        self.fields['email'].help_text = 'Introduceti email'
        self.fields['phone'].help_text = 'Introduceti numarul de telefon'
        self.fields['adress'].help_text = 'Introduceti adresa'
        self.fields['raiting'].help_text = 'Introduceti raiting-ul'
        self.fields['date_order'].initial = datetime.datetime.now
        self.fields['title'].queryset = Menu.objects.filter(date_day=datetime.datetime.today().date())

    class Meta:
        model = Order
        fields = ('__all__')

    def clean(self):
        cleaned_data = self.cleaned_data
        return cleaned_data


    def clean_date_order(self):
        date_order = self.cleaned_data['date_order']
        if date_order < datetime.date.today():
            raise forms.ValidationError("Data nu poate fi din trecut!")
        return date_order

restaurant/views.py
from django.http import HttpResponse
from django.template import loader
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Menu, ORDER_SHIPPING, ORDER_PROCESSING,ORDER_ENDED
from .forms import MenuForm, OrderForm
from django.shortcuts import render
from django.contrib import messages
from restaurant.models import Menu, Order
from rest_framework import viewsets, status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from restaurant.serializers import MenuSerializer, OrderSerializer,InfoSerializer
from datetime import datetime, timedelta
from django.http import HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import math



# from snippets.models import Snippet
# from snippets.serializers import SnippetSerializer
# from django.http import Http404
# from rest_framework.views import APIView
# from rest_framework import status




def index(request):
    all_menus=Menu.objects.all().order_by('-date_day')
    template=loader.get_template('restaurant/menu_list.html')
    context={
        "all_menus":all_menus,
    }
    return HttpResponse(template.render(context, request))

def detail(request, menu_id):
    #import ipdb; ipdb.set_trace();
    menu=Menu.objects.get(pk=menu_id)
    order_list=Order.objects.filter(title__pk=menu_id)
    template=loader.get_template('restaurant/view_menu.html')
    total=0
    count=0
    average=0
    for order in order_list:
        if order.raiting != 0:
            total+= order.raiting
            count+=1
    try:
        average=total/count
    except:
        average=0
    context={
        "menu":menu,
        "order_list":order_list,
        "average":math.floor(average * 10)/10
    }
    return HttpResponse(template.render(context, request))

def index_o(request):
    all_orders_list=Order.objects.all()
    paginator = Paginator(all_orders_list, 15) # Show 15 contacts per page
    page = request.GET.get('page')
    try:
        all_orders = paginator.page(page)
    except PageNotAnInteger:
    # If page is not an integer, deliver first page.
        all_orders = paginator.page(1)
    except EmptyPage:
    # If page is out of range (e.g. 9999), deliver last page of results.
        all_orders = paginator.page(paginator.num_pages)
    template=loader.get_template('restaurant/order_list.html')
    context={
        "all_orders":all_orders,
    }
    return HttpResponse(template.render(context, request))


def detail_o(request, order_id):
    #import ipdb; ipdb.set_trace();
    order=Order.objects.get(pk=order_id)
    template=loader.get_template('restaurant/view_order.html')
    context={
        "order":order,
    }
    return HttpResponse(template.render(context, request))

def index_t(request):
    all_menus=Menu.objects.filter(date_day=datetime.today().date())
    template=loader.get_template('restaurant/todays_menu.html')
    context={
        "all_menus":all_menus,
    }
    return HttpResponse(template.render(context, request))

def post_new(request):
    if request.method == 'GET':
        form = MenuForm()
    elif request.method == 'POST':
        form = MenuForm(data=request.POST)
        # import ipdb; ipdb.set_trace();
        if form.is_valid():
            form.save()
            messages.success(request, "Success!")
        # else:
        #     # pass
        #     messages.error(request, "Error 411: Length Required")
    return render(request, 'restaurant/post_edit.html', {'form': form})



def change(request, order_id):
    u = Order.objects.get(pk=order_id)
    if u.status == ORDER_PROCESSING:
        u.status=ORDER_SHIPPING
        u.save()
        messages.success(request, "The order was sent!")
    else:
        messages.error(request, "The order was NOT sent! ")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# sandru
def post_order(request):

    if request.method == 'GET':
        form = OrderForm()
    elif request.method == 'POST':
        # orders = Order.objects.all()
        #data = request.data
        form = OrderForm(data=request.POST)
        if form.is_valid():
            # import  ipdb; ipdb.set_trace();
            order = form.save()

            send_m(order)
        else:
            # pass
            messages.error(request, "Error la scriere")
    return render(request, 'restaurant/post_order.html', {'form': form})

@api_view(['GET', 'POST'])
def MenuViewSet(request):
    if request.method == 'GET':
        menus = Menu.objects.filter(date_day=datetime.today().date())
        serializer = MenuSerializer(menus, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':

        serializer = MenuSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'POST'])
def OrderViewSet(request):
    if request.method == 'GET':
        orders = Order.objects.all()
        serializer = OrderSerializer(orders, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = OrderSerializer(data=request.data)
        if serializer.is_valid():
            order=serializer.save()
            # import ipdb; ipdb.set_trace();
            send_m(order)

            return Response("Comanda realizata de succes!", status=status.HTTP_201_CREATED)
        return Response("Comanda esuata!", status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'POST'])
def InfoViewSet(request):
    if request.method == 'POST':
        # import ipdb; ipdb.set_trace();
        data=request.data
        sir=data['sir']
        ids = sir.split("-")
        menu_id=ids[0]
        order_id=ids[1]
        try:
            if len(data['sir'])>=3 and ('-' in data['sir']) and len(ids)==2 and menu_id.isnumeric() and order_id.isnumeric() :

                order= Order.objects.get(id=order_id)
                serializer = InfoSerializer(order)
                # import ipdb; ipdb.set_trace();
                menu= Menu.objects.get(id=serializer.data['title'])
                if str(menu.id)==str(menu_id):
                    informatii ={
                    'dish1':menu.dish1,
                    'dish2':menu.dish2,
                    'desert':menu.desert,
                    'status': serializer.data['status'],
                    'sir':sir
                    }
                else:
                    return Response("Meniul dat nu corespunde", status=status.HTTP_400_BAD_REQUEST)
            else:
                return Response("Meniul dat nu corespunde", status=status.HTTP_400_BAD_REQUEST)
        except Exception as err:
            return Response({"details":str(err)}, status=status.HTTP_400_BAD_REQUEST)
        return Response(informatii,status=status.HTTP_200_OK)



@api_view(['GET', 'POST'])
def RaitingViewSet(request):
    if request.method == 'POST':
        # import ipdb; ipdb.set_trace();
        try:
            data=request.data
            sir=data['sir']
            ids = sir.split("-")
            menu_id=ids[0]
            order_id=ids[1]
        except Exception as err:
             return Response({"details":str(err)}, status=status.HTTP_400_BAD_REQUEST)
        try:
            if len(data['sir'])>=3 and ('-' in data['sir']) and float(data['rating'])>0 and float(data['rating'])<=5.0 and len(ids)==2 and menu_id.isnumeric() and order_id.isnumeric():
                order= Order.objects.get(id=    order_id)
                if str(order_id)==str(order.id):
                    order.raiting=data['rating']
                    order.status=ORDER_ENDED
                    order.save()
                else:
                    return Response("Rating invalid", status=status.HTTP_400_BAD_REQUEST)
            else:
                return Response("Rating invalid", status=status.HTTP_400_BAD_REQUEST)

        except Exception as err:
             return Response({"details":str(err)}, status=status.HTTP_400_BAD_REQUEST)
        return Response("Comanda finalizata cu succes",status=status.HTTP_200_OK)





def send_m(order):
    subject = "Order confirmation"
    msg = "Va multumim pentru comanda facuta " + order.name + ". Ati comandat urmatorul meniu :" + order.title.title + " si contine: Felul 1 - " + order.title.dish1 + ", Felul 2 - " + order.title.dish2 +", Desert - " + order.title.desert + ". Numarul dvs de comanda este :" + str(order.title.pk) +"-" + str(order.pk)
    send_mail(subject, msg, "testlunch72@gmail.com", [order.email])

restaurant/templates/restaurant/index.html
{% load staticfiles %}
<html>
<head>
<title>Restaurant</title>
    <link rel="stylesheet" href="{% static 'dist/assets/css/app.css' %}">
</head>
<body>
    <nav class="navbar">
      <!-- Left side of navbar -->
      <div class="navbar__item navbar__item--left">
        <a href="{% url 'restaurant:index'%}"><img class="logo" src="{% static 'img/logo.png' %}"></a>
        <!-- Navbar menu -->
        <div class="dropdown">
          <span>Welcome &#x25bc;</span>
          <div class="dropdown__content">
            <ul class="dropdown__list">
              <li>
                <a href="{% url 'restaurant:index'%}">Home/Menu table</a>
            </li>
            <li>
                <a href="{% url 'restaurant:post_new'%}">Add menu</a>
            </li>
            <li>
                <a href="{% url 'restaurant:post_order'%}">Add order</a>
            </li>
            <li>
                <a href="{% url 'restaurant:index_t'%}">Today's menu</a>
            </li>
            <li>
                <a href="{% url 'restaurant:index_o'%}">Orders</a>
            </li>
        </ul>
    </div>
</div>
<!-- End Navbar menu -->
</div>
<!-- Right side of navbar -->
<div class="navbar__item--right">
    <a class="link" href="#">User</a>
    <img class="avatar" src="{% static 'img/user.jpg' %}">
</div>
</nav>
<!-- End Navbar section -->


{% block content %}

{% endblock %}


<footer></footer>
<script src="{% static 'dist/assets/js/app.js' %}"></script>
</body>

</html>

restaurant/templates/restaurant/menu_list.html
{% extends 'restaurant/index.html' %}
{% load staticfiles %}
{% block content %}
<!-- Lunch history section -->
<section class="lunch">
  <table class="lunch__table">
    <thead>
      <tr>
        <th>Data</th>
        <th>Titlu</th>
        <th>Actiuni</th>
      </tr>
    </thead>
    <tbody>
    {% for menu in all_menus%}

      <tr>
        <td>
          <p>{{menu.date_day}}</p>
        </td>
        <td>
          <p>{{menu.title}}</p>
        </td>
        <td>
          <a class="button button--large link" href="{% url 'restaurant:detail' menu.pk %}">Vizualizare</a>
        </td>
      </tr>
      {%endfor%}

    </tbody>
  </table>
</section>
<!-- End Lunch history section -->
{% endblock %}

restaurant/templates/restaurant/order_list.html
{% extends 'restaurant/index.html' %}
{% load staticfiles %}
{% block content %}
<div class="menu__container menu__container--xs">
  <div class="form">
    <h1>Order list</h1>
    <ul class="menu__list">
      {% for order in all_orders%}
      <li><a href="{% url 'restaurant:detail_o' order.pk %}"> {{order.name}} - {{order.title}}</a></li>
      {%endfor%}
    </ul>
    <div class="pagination">
      <span class="step-links">
        {% if all_orders.has_previous %}
        <a class="button button--small link" href="?page={{ all_orders.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ all_orders.number }} of {{ all_orders.paginator.num_pages }}.
        </span>

        {% if all_orders.has_next %}

        <a class="button button--small link" href="?page={{ all_orders.next_page_number }}">next</a>
        {% endif %}
      </span>
    </div>
  </div>
</div>

{% endblock %}

restaurant/templates/restaurant/post_edit.html
{% extends 'restaurant/index.html' %}
{% load staticfiles %}

{% block content %}

<!-- Add menu section -->
<section class="container">
    <form method="POST" class="form">{% csrf_token %}
        <h1>Add menu</h1>
        {% for field in form %}

        {{ field }}
        {{ field.errors }}
        {% if field.help_text %}
        <p class="input__notification">{{ field.help_text|safe }}</p>
        {% endif %}

        {% endfor %}
        <input type="submit" class="form__input button button--large" value="Save">

        <!-- Message status -->
        {% if messages %}
            {% for message in messages %}
            <p{% if message.tags %} class="alert alert--big form__notification {{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        {% endif %}
    </form>
</section>
<!-- End Add menu section -->

{% endblock %}

restaurant/templates/restaurant/post_order.html
{% extends 'restaurant/index.html' %}
{% load staticfiles %}

{% block content %}
<section class="container">

    <form method="POST" class="form">{% csrf_token %}
    <h1>Add your order</h1>
        {% for field in form %}
            {{ field.label_tag }} {{ field }}
            {{ field.errors }}
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}

        {% endfor %}
        <button type="submit" class="button button--large">Save</button>
    </form>
</section>
{% endblock %}

restaurant/templates/restaurant/todays_menu.html
{% extends 'restaurant/index.html' %}
{% load staticfiles %}
{% block content %}
<!-- Today's menu section -->
<div class="menu__container menu__container--small">

  <h1>Today's menu</h1>

  <ul class="menu__list">
    {% for menu in all_menus%}
    <li><a href="{% url 'restaurant:detail' menu.pk %}"> {{menu.title}}</a></li>
    {%endfor%}
  </ul>

  <div class="pagination">
    <span class="step-links">
      {% if all_menus.has_previous %}
      <a class="button button--small link" href="?page={{ all_menus.previous_page_number }}">previous</a>
      {% endif %}
      <span class="current">
        Page {{ all_menus.number }} of {{ all_menus.paginator.num_pages }}.
      </span>
      {% if all_menus.has_next %}
      <a class="button button--small link" href="?page={{ all_menus.next_page_number }}">next</a>
      {% endif %}
    </span>
  </div>
</div>

{% endblock %}

restaurant/templates/restaurant/view_menu.html
{% extends 'restaurant/index.html' %}
{% load staticfiles %}

{% block content %}
<!-- Menu details section -->
<section>
  <!-- Menu list -->
  <div class="menu">
   <h1 class="menu__header">Menu details</h1>

   <div class="menu__container menu__container--small">
     <ul class="menu__list">
     <li>
       {{menu.dish1}}
     </li>
     <li>
       {{menu.dish2}}
     </li>
     <li>
       {{menu.desert}}
     </li>
     <li>
       {{menu.date_day}}
     </li>
     <li class="ratingjs">
       {{average}}/5
     </li>
     <li>
        <div class="ratingjs2 stars">
        <span></span>
        </div>
     </li>
   </ul>

    <!-- Message status -->
  {% if messages %}
    {% for message in messages %}
        <p{% if message.tags %} class="alert-success alert alert--small form__notification {{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
  {% endif %}

   </div>
 </div>

<!-- Clients list -->

<div class="menu__container menu__container--big">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Status</th>
        <th>Change status</th>
        <th>Rating</th>
      </tr>
    </thead>
    <tbody>

    {% for obj in order_list%}

      <tr>
        <td>
          <p>{{obj.name}}</p>
        </td>
        <td>
          <p>{{obj.adress}}</p>
        </td>
        <td>
          <p>{{obj.email}}</p>
        </td>
        <td>
          <p>{{obj.phone}}</p>
        </td>
        <td>
          <p>{{obj.get_status_display}}</p>
        </td>
        {% if obj.status == 0 %}
        <td>
          <a class="button button--large link" href="{% url 'restaurant:change' obj.pk  %}">Shipping</a>
        </td>
        {%else%}
        <td></td>
        {%endif%}
        {% if obj.raiting %}
        <td>
       {{obj.raiting}}
        </td>
         {%else%}
        <td></td>
        {%endif%}
      </tr>
      {%endfor%}

    </tbody>
  </table>

</div>
</section>
{% endblock %}

restaurant/templates/restaurant/view_order.html
{% extends 'restaurant/index.html' %}
{% load staticfiles %}


{% block content %}
   <div class="menu__container menu__container--small">
   <h1>Client details</h1>

<ul class="menu__list">
        <li>Name: {{order.name}}</li>
        <li>E-mail: {{order.email}}</li>
        <li>Address: {{order.adress}}</li>
        <li>Phone: {{order.phone}}</li>
</ul>
</div>
{% endblock %}